config/routes.rb
Kurov::Application.routes.draw do
  root "pages#home"    
  get "home", to: "pages#home", as: "home"
  get "inside", to: "pages#inside", as: "inside"
  get "/contact", to: "pages#contact", as: "contact"
  get "/cabinet", to: "pages#cabinet", as: "cabinet"
  post "/emailconfirmation", to: "pages#email", as: "email_confirmation"
  
  get "blog", to: "pages#posts", as: "posts"
  get "blog/:id", to: "pages#show_post", as: "post"    
  devise_for :users, path: '', path_names: {sign_in: 'login', sign_out: 'logout'}
  
  namespace :admin do
    root 'base#index'
    resources :users
    get "posts/drafts", to: "posts#drafts", as: "posts_drafts"
    get "posts/dashboard", to: "posts#dashboard", as: "posts_dashboard"
    resources :posts
  end
  
end

app/models/post.rb
class Post < ActiveRecord::Base
  require 'babosa'
  include R18n::Translated


  # Use friendly_id
  extend FriendlyId
  friendly_id :title, use: :slugged
  
  # Markdown
  before_save { Markdown.update_html(self) }
    
  # Validations
  validates :title, presence: true, length: { maximum: 100 }, uniqueness: true
  validates :content_md, presence: true
  
  # Pagination
  paginates_per 30  
  
  # Relations
  belongs_to :user
  
  # Scopes  
  scope :published, lambda {
    where(draft: false)
    .order("updated_at DESC")
  }
  
  scope :drafted, lambda {
    where(draft: true)
    .order("updated_at DESC")
  }

  def normalize_friendly_id(input)
    input.to_s.to_slug.normalize(transliterations: :russian).to_s
  end
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < Admin::BaseController
  
  before_action :set_post, only: [
    :edit,
    :update,
    :destroy
  ]
  
  
  def dashboard
    @published_post_count = Post.published.count
    @draft_post_count = Post.drafted.count
    @published = Post.published.page(params[:page]).per(50)
    @drafted = Post.drafted.page(params[:page]).per(50) 
  end
  
  def index
    @posts = Post.published.page(params[:page]).per(50)
  end
  
  def drafts
    @posts = Post.drafted.page(params[:page]).per(50)    
  end
  
  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    if @post.save
      redirect_to admin_posts_dashboard_path, notice: "Новая статья успешно сохранена."
    else
      flash[:alert] = "Ошибка! Статья не была сохранена!"
      render :new
    end
  end

  def edit
  end

  def update
    @post.slug = nil
    if @post.update(post_params)
      redirect_to admin_posts_dashboard_path, notice: "Статья успешно отредактирована."
    else
      flash[:alert] = "Ошибка! Статья не была сохранена!"
      render :edit
    end
  end

  def destroy
    @post.destroy
    redirect_to admin_posts_path, notice: "Статья была успешно удалена."
  end
  
  
  private
  
  def set_post
    @post = Post.friendly.find(params[:id])
  end
  
  def post_params
    params.require(:post).permit(
    :title,
    :content_md,
    :draft,
    :updated_at
    )
  end
  
  
end

app/views/admin/posts/_form.html.haml
-#- if @post.errors.any?
-#  %ul
-#    - @post.errors.full_messages.each do |msg|
-#      %li= msg
= bootstrap_form_for [:admin, @post], role: "form" do |f|
  .form-group
    .row
      .col-xs-12
        = f.text_field :title, :autofocus => true, placeholder: "Заголовок статьи...", label: "Заголовок"
  .form-group
    .row
      .col-xs-12
        = f.text_area :content_md, rows: 15, placeholder: "Основной текст статьи...", label: 'Основной текст'
  .form-group
    .row
      .col-xs-12
        = f.check_box :draft, label: "сохранить в черновики"
        
  .form-group
    
    .row
      .col-xs-12
        = f.datetime_select :updated_at, label: "Дата публикации"
  %hr
    
  .row
    .col-xs-12.padded
      %button.btn.btn-primary
        %i.fa.fa-plus-square
        Сохранить!
      = link_to "- Отмена", admin_posts_dashboard_path

     

app/views/admin/posts/dashboard.html.haml
- title("Posts Dashboard")
.row
  .col-sm-8
    %h2.page-title
      Статьи
      %small Панель управления статьями
  .col-sm-4
    .pull-right.space-top-md= link_to "Создать новую статью", new_admin_post_path, class: "btn btn-success"

%p= link_to "Вернуться на главную", admin_root_path
%hr/
.row
  .col-sm-6
    %h4 
      Опубликованные статьи(#{link_to @published_post_count, admin_posts_path})
    %ul.fa-ul
      - @published.each do |post|
        %li.margin-md-down
          %i.fa.fa-arrow-circle-o-right.small
          = link_to post.title, edit_admin_post_path(post.slug)
          %br
          %small.x-small-text
            Опубликовано
            = timeago_tag post.updated_at 
  .col-sm-6
    %h4
      В черновиках(#{link_to @draft_post_count, admin_posts_drafts_path})
    %ul.fa-ul
      - @drafted.each do |post|
        %li.margin-md-down
          %i.fa.fa-arrow-circle-o-right.small>
          = link_to post.title, edit_admin_post_path(post.slug)
          %br
          %small.x-small-text
            Опубликовано
            = timeago_tag post.updated_at 
  

app/views/admin/posts/drafts.html.haml
- title("Черновики")
%h2.page-title
  Черновики
  %small Статьи, сохраненные в черновики
%p= link_to "Вернуться назад", admin_posts_dashboard_path
%hr/
%p.pagination-summary= "Всего статей: #{@posts.count}"
= paginate @posts
%hr/
%ul.fa-ul
  - @posts.each do |post|
    %li.margin-md-down
      %i.fa.fa-arrow-circle-o-right.small>
      \&nbsp;&nbsp;
      \#{link_to post.title, edit_admin_post_path(post.slug)}
      %br/
      %small.x-small-text
        about #{time_ago_in_words(post.updated_at)} ago
%hr/
= paginate @posts

app/views/admin/posts/edit.html.haml
- title("Редактирование статьи '#{@post.title}'")
%h3.page-title
  Редактирование статьи
  %small= "'#{@post.title}'"
%p
  = link_to "Назад", admin_posts_dashboard_path
%hr
= render 'form'
%hr
= link_to "<i class='fa fa-minus-square'></i> Удалить статью".html_safe,admin_post_path(@post), method: :delete, class: "btn btn-small btn-danger"

app/views/admin/posts/index.html.haml
- title("Опубликованные статьи")
%h3.page-title
  Статьи
  %small Опубликованные
%p= link_to "Вернуться назад", admin_posts_dashboard_path
%hr/
%p.pagination-summary= "Всего статей: #{@posts.count}"
= paginate @posts
%hr/
%ul.fa-ul
  - @posts.each do |post|
    %li.margin-md-down
      %i.fa.fa-arrow-circle-o-right.small>
      = link_to post.title, edit_admin_post_path(post.slug)
      %br
      %small.x-small-text
        Опубликовано
        = timeago_tag post.updated_at 
%hr/
= paginate @posts

app/views/admin/posts/new.html.haml
- title("New post")
%h3.page-title Add a new post
%p= link_to "Back to dashboard", admin_posts_dashboard_path
%hr/
= render 'form'