config/routes.rb
Kurov::Application.routes.draw do
  root "pages#home"    
  get "home", to: "pages#home", as: "home"
  get "inside", to: "pages#inside", as: "inside"
  get "/contact", to: "pages#contact", as: "contact"
  get "/cabinet", to: "pages#cabinet", as: "cabinet"
  post "/emailconfirmation", to: "pages#email", as: "email_confirmation"
  
  get "blog", to: "pages#posts", as: "posts"
  get "blog/:id", to: "pages#show_post", as: "post"    
  devise_for :users, path: '', path_names: {sign_in: 'login', sign_out: 'logout'}
  
  namespace :admin do
    root 'base#index'
    resources :users
    get "posts/drafts", to: "posts#drafts", as: "posts_drafts"
    get "posts/dashboard", to: "posts#dashboard", as: "posts_dashboard"
    resources :posts
  end
  
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
  before_filter :require_admin!
  
  def index
    @last_signups = User.last_signups(10)
    @last_signins = User.last_signins(10)
    @user = User.first
    @count = User.users_count 
    @post_count = Post.count
  end
end

app/views/admin/base/index.html.haml
- title("Панель администратора")
%h2
  Управление
  %small Панель администратора
.row
  .col-sm-4
    -#%h3 Разделы:
    -#%h4
    -#  = link_to "Пользователи", admin_users_path
    -#  %small
    -#    = "#{@count}" 
    %h4
      = link_to "Статьи", admin_posts_dashboard_path
      %small
        = "#{@post_count}"
    %hr/

            
  .current-session-block.small-text
    %h6 Текущая сессия:
    %ul.list-unstyled
      %li
        = link_to current_user.email, edit_admin_user_path(current_user)
        %br
        %small
          Вход:
          - unless current_user.current_sign_in_at.nil?
            = timeago_tag(current_user.current_sign_in_at)
            
          - else
            0
        %br
        %small IP: #{current_user.current_sign_in_ip}