config/routes.rb
Kurov::Application.routes.draw do
  root "pages#home"    
  get "home", to: "pages#home", as: "home"
  get "inside", to: "pages#inside", as: "inside"
  get "/contact", to: "pages#contact", as: "contact"
  get "/cabinet", to: "pages#cabinet", as: "cabinet"
  post "/emailconfirmation", to: "pages#email", as: "email_confirmation"
  
  get "blog", to: "pages#posts", as: "posts"
  get "blog/:id", to: "pages#show_post", as: "post"    
  devise_for :users, path: '', path_names: {sign_in: 'login', sign_out: 'logout'}
  
  namespace :admin do
    root 'base#index'
    resources :users
    get "posts/drafts", to: "posts#drafts", as: "posts_drafts"
    get "posts/dashboard", to: "posts#dashboard", as: "posts_dashboard"
    resources :posts
  end
  
end

app/views/layouts/_banner.html.haml
.banner
  .banner-inner
    %span.divider
    %span Нам 500 лет

app/views/layouts/_footer.html.haml
#footer
  .container
    .row.footer-first-row
      .col-xs-12.text-center
        %p
          %small
            \&copy; 2014 - Yourself!
            %br/
            Assembled with #{link_to "Kurov", "#"}
:javascript
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
  
  ga('create', 'UA-XXXXXX-XX', 'auto');
  ga('send', 'pageview');

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name == "notice" ? "success" : "danger"}"}
      %button.close.pull-left{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} &times;
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.haml
%nav.navbar.navbar-default
  .container
    .row.space-top-sm
      .col-lg-1.hidden-md
        
      .col-xs-12.col-sm-9.col-lg-8.nav-center
        .intro
          %h3 Более 30 лет с верой в человека
          %h2 Вадим Александрович Куров
          %h5 психолог - психиатр - психотерапевт
        %ul.nav.navbar-nav
          = render 'layouts/navigation_links'
      .col-xs-6.col-sm-3.col-lg-2.nav-contact
        %span +7 (495) 514-44-22
        .clearfix
        %span +7 (495) 452-03-56
        .clearfix
        %span Kurov07@mail.ru
        .pull-right= image_tag "shape4.png", size: '120', style: "opacity:0.7;"

app/views/layouts/_navigation_links.html.haml
%li= link_to "Главная", root_path
%li= link_to "Кабинет", cabinet_path
%li.dropdown
  = link_to "Материалы", "#", class: "dropdown-toggle", 'data-toggle'=>"dropdown", role: :button, "area-expanded"=>"false"
  %ul.dropdown-menu(role="menu")
    %li=link_to "Психология или психиатрия", "#"
    %li=link_to "Как выбрать терапевта", "#"
    %li=link_to "Очень длинное название ну очень длинной статьи", "#"
%li= link_to "Блог", posts_path 
%li= link_to "Отзывы", '#'
%li= link_to "Контакты", contact_path
- if user_signed_in?

  %li= link_to "Управление", admin_root_path
  %li= link_to "Выход", destroy_user_session_path, data:{method: :delete}

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no", :name => "viewport"}/
    %title= @title || "Kurov"
    = favicon_link_tag 'favicon.ico'
    = favicon_link_tag 'apple-touch-icon.png', rel: 'apple-touch-icon', type: 'image/png'
    = stylesheet_link_tag "application", media: "all"

    = javascript_include_tag "application"
    = csrf_meta_tags
    = timeago_script_tag
    
  %body
    //#left
    //#top
    //#right
    //#bottom
    #wrap
      %header

        = render 'layouts/navigation'
      .container
        = render 'layouts/messages'
        .row
          .col-sm-12
            = yield
      = render 'layouts/footer'

    